05 UploadCertificateServiceMockTest, SurveyServiceMockTest, StudyServiceMockTest
Sage-Bionetworks/BridgeServerLogic pull request #12
Opened 2019-05-24 21:23 UTC by alxdarksage

2019-05-28 07:00 UTC, DwayneJengSage requested changes

2019-05-28 07:00 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/services/StudyService.java
> +                BridgeConfigFactory.getConfig().getPropertyAsList(CONFIG_STUDY_WHITELIST)));
I think you intended this to be the passed in bridgeConfig and not the static BridgeConfigFactory.getConfig().

2019-05-28 07:00 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/services/SurveyServiceMockTest.java
>  public class SurveyServiceMockTest {
Missing tests:

* versionSurvey()
* getSurveyAllVersions()

2019-05-28 23:48 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/services/StudyService.java
> +                BridgeConfigFactory.getConfig().getPropertyAsList(CONFIG_STUDY_WHITELIST)));
Yes. Changed.

2019-05-28 23:59 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/services/SurveyServiceMockTest.java
>  public class SurveyServiceMockTest {
Added

2019-05-29 06:51 UTC, DwayneJengSage approved these changes

2019-05-29 18:01 UTC, merged